-- =====================================================================
--    DATA BASE – FINANCIAL MANAGEMENT SYSTEM  (Initial Version)
-- =====================================================================


-- ============================
--  Usuário
-- ============================
CREATE TABLE usuario (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL
);

-- Usuário padrão inicial
INSERT INTO usuario (nome) VALUES ('Usuário Padrão');



-- ============================
--  Categoria Base
-- Ex: Alimentação, Assinaturas, Investimentos
-- ============================
CREATE TABLE categoria_base (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    nome VARCHAR(100) NOT NULL,
    FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);



-- ============================
--  Categoria Mensal
-- Orçamento para um mês específico (ex: Alimentação - Janeiro)
-- ============================
CREATE TABLE categoria_mensal (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    categoria_base_id BIGINT NOT NULL,
    mes_referencia DATE NOT NULL,
    valor_planejado DECIMAL(19, 2) NOT NULL,
    FOREIGN KEY (categoria_base_id) REFERENCES categoria_base(id)
);



-- ============================
-- Reserva (Cofrinho)
-- Pode ser individual ou coletiva
-- ============================
CREATE TABLE reserva (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    meta_valor DECIMAL(19, 2)
);



-- ============================
-- 5. Tabela de Participantes da Reserva
-- Permite reservas individuais OU coletivas
-- ============================
CREATE TABLE reserva_usuario (
    reserva_id BIGINT NOT NULL,
    usuario_id BIGINT NOT NULL,
    PRIMARY KEY (reserva_id, usuario_id),
    FOREIGN KEY (reserva_id) REFERENCES reserva(id),
    FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);



-- ============================
-- 6. Transação
-- Pode apontar para categoria mensal OU para reserva
-- ============================
CREATE TABLE transacao (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    valor DECIMAL(19, 2) NOT NULL,
    tipo VARCHAR(20) NOT NULL, -- 'entrada' ou 'saida'
    data_transacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    categoria_mensal_id BIGINT,
    reserva_id BIGINT,

    FOREIGN KEY (categoria_mensal_id) REFERENCES categoria_mensal(id),
    FOREIGN KEY (reserva_id) REFERENCES reserva(id),
    FOREIGN KEY (usuario_id) REFERENCES usuario(id)
);

