-- =====================================================================
-- V1: INITIAL SCHEMA (Financial Management System)
-- =====================================================================

--  APP USER (Avoided 'user' as it is a reserved keyword)
-- Stores the cycle day (e.g., user receives salary on the 15th).
CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150),
    cycle_start_day INT DEFAULT 1 CHECK (cycle_start_day BETWEEN 1 AND 31)
);

-- Insert Default User (Owner)
INSERT INTO app_user (name, cycle_start_day) VALUES ('Default User', 1);


--  BASE CATEGORY (The Blueprint)
-- Example: "Groceries", "Transport". Created once.
CREATE TABLE base_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    name VARCHAR(100) NOT NULL,
    color_hex VARCHAR(7), -- Ex: #FF0000 for charts
    is_active BOOLEAN DEFAULT TRUE
);


--  MONTHLY CATEGORY (The Instance)
-- Example: "Groceries for Nov/2025". Holds planned vs spent values.
CREATE TABLE monthly_category (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_category_id BIGINT NOT NULL REFERENCES base_category(id),
    
    reference_month DATE NOT NULL, -- Always the 1st of the month (e.g., 2025-11-01)
    planned_amount DECIMAL(19, 2) NOT NULL DEFAULT 0.00,
    amount_spent DECIMAL(19, 2) DEFAULT 0.00, -- Updated via code/trigger
    
    -- Ensures we don't duplicate the same category for the same month
    UNIQUE (base_category_id, reference_month)
);


--  RESERVE (Savings/Goals)
-- Shared entity (N:N), so no direct user_id here. See table 5.
CREATE TABLE reserve (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    target_amount DECIMAL(19, 2),
    deadline DATE
);


--  RESERVE MEMBER (Many-to-Many)
-- Who participates in this reserve?
CREATE TABLE reserve_member (
    reserve_id BIGINT NOT NULL REFERENCES reserve(id),
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    PRIMARY KEY (reserve_id, user_id)
);


--  FINANCIAL TRANSACTION (The Cash Flow)
-- Records every income or expense.
CREATE TABLE financial_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL REFERENCES app_user(id),
    
    amount DECIMAL(19, 2) NOT NULL,
    type VARCHAR(20) NOT NULL, -- 'INCOME' or 'EXPENSE'
    description VARCHAR(255),
    transaction_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- The transaction is linked to EITHER a Monthly Category OR a Reserve
    monthly_category_id BIGINT REFERENCES monthly_category(id),
    reserve_id BIGINT REFERENCES reserve(id),

    -- Constraint to ensure data integrity:
    -- Must be Category OR Reserve OR neither (if it's a raw Salary Income)
    CONSTRAINT chk_destination CHECK (
        (monthly_category_id IS NOT NULL AND reserve_id IS NULL) OR
        (monthly_category_id IS NULL AND reserve_id IS NOT NULL) OR
        (monthly_category_id IS NULL AND reserve_id IS NULL)
    )
);